name: "Theron Properties"
author: "Kennedy"
email: "kennedy@theronproperties.com"
url: "http://theronproperties.com"
title: "Theron Properties"
description:
permalink: pretty
markdown: kramdown
highlighter: rouge

include: ['_pages']

exclude:
  - CNAME
  - editorconfig.txt
  - Gemfile
  - Gemfile.lock
  - README.md
  - RAKEFILE

gems:
  - jekyll-assets
  - uglifier
  - sass

assets:
  dirname: assets
  baseurl: /assets/
  cache: false

sources:
  - _assets/fonts
  - _assets/images
  - _assets/javascripts
  - _assets/stylesheets

navigation:
- text: About
  url: /about/
- text: Rentals
  url: /rentals/
- text: Contact
  url: /contact/
